### ISSUE TITLE
Fix Buffer is undefined for react-script 5.0.0

### ISSUE THREAD

**Issue by FrameMuse** [marcin-piela/react-fetching-library#158]
There is a error using react-script 5.0.0
![image](https://user-images.githubusercontent.com/53980482/154489795-d77b4a0d-7a29-468b-8acf-113651eaf12b.png)
![image](https://user-images.githubusercontent.com/53980482/154489871-2e30125a-caf0-4cae-8077-b286aa8fdbc8.png)

Fix:
- `npm i buffer`
- add `import { Buffer } from "buffer"`
or:
- use Uint8Array, it seems it works as Buffer in this case

**Comment by ajfunelas** [comment]
My temporary workaround was downgrading from ```react-scripts 5.0.1``` to ```4.0.3```
