### ISSUE TITLE
SSR with cache ?

### ISSUE THREAD

**Issue by revskill10** [marcin-piela/react-fetching-library#21]
Is there any method from `cache` to return cache data to client ?

**Comment by ntucker** [comment]
That would be pretty easy if https://github.com/marcin-piela/react-fetching-library/issues/13 happens. Then you can pull the state directly from the redux store. You won't have to use redux in the browser as you could have a split point based on if it was running server-side.

**Comment by marcin-piela** [comment]
There is method for that:
```
client.cache.get(action)
```

And it's working on server side for our simple cache provider.

**Example app for next.js framework (responses are cached for 10s on server side):**

`next.config.js`:
```
const withTM = require('next-transpile-modules')

module.exports = withTM({
  transpileModules: ['react-fetching-library']
});
```

`client.js`
```
import { createClient, createCache } from "react-fetching-library";

const cache = createCache(
  (action) => {
    return action.method === 'GET';
  },
  (response) => {
    return new Date().getTime() - response.timestamp < 10000;
  },
);

const client = createClient({
  cacheProvider: cache,
});

export default client;

```

`pages/_app.js`

```
import App, { Container } from 'next/app';
import 'isomorphic-unfetch';

import { ClientContextProvider } from "react-fetching-library";
import client from '../client';

class MyApp extends App {
  render () {
    const { Component, pageProps } = this.props

    return (
      <Container>
        <ClientContextProvider client={client}>
          <Component {...pageProps} />
        </ClientContextProvider>
      </Container>
    )
  }
}

export default MyApp
```

`pages/index.js`

```
import React from "react";
import client from "../client";

const action = {
  method: "GET",
  endpoint: "https://private-34f3a-reactapiclient.apiary-mock.com/users"
};

const Users = ({ loading, payload, error, query }) => {
  return (
    <div>
      {loading && <span>Loading</span>}

      {error && <span>Error</span>}

      {payload && <span>{payload.length}</span>}

      <button onClick={query}>Reload</button>
    </div>
  );
};

Users.getInitialProps = async ({ req }) => {
  // fetch
  const res = await client.query(action);

  // get data from cache
  console.log(client.cache.get(action));

  return res;
}

export default Users;
```

**Comment by revskill10** [comment]
@marcin-piela I need a simple API like `redux`.
```js
const cache = ...
const html = React.renderToString(<App />);
const serialized = serialize(cache.getState());
```

**Comment by marcin-piela** [comment]
For now only `items` method is available to get object with all cached responses, please provide your use case so we will think about solution 👍

**Comment by revskill10** [comment]
@marcin-piela My use case is as in Redux use case.
You create a redux store.
You render React component.
You then `store.getState()` to send to client.
Client then hydrates state from it.

**Comment by marcin-piela** [comment]
@revskill10 new version 1.2.0 supports your usecase

Documentation:
https://marcin-piela.github.io/react-fetching-library/#/?id=ssr-server-side-rendering

Codesandbox example:
https://codesandbox.io/s/github/marcin-piela/react-fetching-library/tree/master/examples/ssr

`Cache` now allows to get/set items:
```js
//on server:
const cachedItems = client.cache.getItems()

//send to client:
client.cache.setItems(cachedItems)
```
