### ISSUE TITLE
Suggestion: Publish code as cjs

### ISSUE THREAD

**Issue by pgsandstrom** [marcin-piela/react-fetching-library#26]
Currently, when adding this dependency to a Create React App project, the tests will start to fail. This is due to the published code using es syntax like import/export.

It is quite common to either just publish cjs-code, or perhaps put the es code in their own "es" folder for people who want to transpile it themselves. The first good example I can think of is https://github.com/FezVrasta/react-popper which I think has quite good code.

In the meantime, a workaround for people using Create React App or a configuration like it is to add `--transformIgnorePatterns "node_modules/(?!(react-fetching-library)/)"` to the jest-command.

**Comment by marcin-piela** [comment]
I'll do it 👍 
I've checked it with CRA with TS and it's working fine, maybe that's why I didn't catch it. The problem exists in next.js as well. Thanks for add an issue.

**Comment by marcin-piela** [comment]
@pgsandstrom try brand new 1.2.2 version 😄
