### ISSUE TITLE
Get request without options request

### ISSUE THREAD

**Issue by jonwalz** [marcin-piela/react-fetching-library#27]
Hi, sorry for the newbie question but I'm having a hard time getting this library to make a get request without first sending an options request. 

I'm simply trying to fetch my treehouse points from this endpoint:
`https://teamtreehouse.com/jonathanwalz.json`

Using the fetch api, it works perfectly:
`fetch('https://teamtreehouse.com/jonathanwalz.json')`

Is there anyway to make a get without options? Thanks in advance.

**Comment by jonwalz** [comment]
Ended up making a node server as a proxy. I'm still curious to know if there's a way to disable the options request though

**Comment by marcin-piela** [comment]
Hmmm, it' weird cause this lib uses `fetch` API, the difference is adding header by default:
```
          headers: { ...{ 'Content-Type': 'application/json; charset=utf-8' }, ...headers },
```

If you use `create-react-app` you can add proxy parameter to `package.json` instead of creating proxy on your own: https://facebook.github.io/create-react-app/docs/proxying-api-requests-in-development
