### ISSUE TITLE
Use useSuspendQuery more than once from same component

### ISSUE THREAD

**Issue by mibu1990** [marcin-piela/react-fetching-library#28]
I need to refresh view after adding new data. I know that "useQuery" hook has that ability by calling "query" function, however I would like to have similar result with "useSuspenseQuery". It is also possible by changing action, which is used as cache key, but I need to call it again with same action as before. Is it possible somehow to clean that cache or any other way of using "useSuspenseQuery" hook multiple times from same component without changing action ?

**Comment by marcin-piela** [comment]
@mibu1990 thanks for add this issue.

It has to be done on library side (clear suspense cache and re-run fetch). I'll try to do it before next release (probably tomorrow)

**Comment by marcin-piela** [comment]
Released in 1.2.3 version
Docs: https://marcin-piela.github.io/react-fetching-library/#/?id=usesuspensequery
