### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by BenQoder** [marcin-piela/react-fetching-library#37]
Am I Right To Assume This Will Not Work On React Native?.
Documentation says React Dom is a requirement

**Comment by marcin-piela** [comment]
@BenQoder good catch, in package.json there is react-dom as peerDeps but is not required at all (not used in code) so it should work on react native well, but please check it and leave feedback here :)

**Comment by marcin-piela** [comment]
I will update package.json soon

**Comment by BenQoder** [comment]
Alright... I Will Leave A Feedback Once I Use It To Solve My Case Scenario.. Maybe Tomorrow

**Comment by BenQoder** [comment]
Works With React Native... I've Not Tested All Features Though..

**Comment by abgaryanharutyun** [comment]
hey, @marcin-piela @BenQoder  I'm getting an error when I want to use useMutation in my react native application. 

Im getting this error message 
```
Buffer is not defined
```

**Comment by marcin-piela** [comment]
@abgaryanharutyun try to install polyfill for buffer https://github.com/feross/buffer

```
npm install buffer
```

**Comment by abgaryanharutyun** [comment]
Thanks for replying. But it's not helped me. I'm getting some error.

**Comment by abgaryanharutyun** [comment]
I want to use it to react-native.  and useMutation worked very well but useQuery not.

**Comment by marcin-piela** [comment]
Cause only `useQuery` uses `Buffer.from`

https://github.com/facebook/react-native/issues/14796

try this:

```
npm install buffer

global.Buffer = global.Buffer || require('buffer').Buffer
```

**Comment by abgaryanharutyun** [comment]
Thanks @marcin-piela it's  worked. Thanks, lot
