### ISSUE TITLE
Issue With Request Inceptor And Redux State

### ISSUE THREAD

**Issue by BenQoder** [marcin-piela/react-fetching-library#42]
I Am Trying To Get Access Token From Redux State Like This.
I Don`t Know What I Am Doing Wrong But When The Access Code Changes It Doesn't Change In The Request Inceptor. That Is The Old Access Code Is Still Used After Access Code Has Change In Redux State

```js
const { store } = configureStore();

const apiTokenInterceptor = host => client => async action => {
	const state = store.getState();
	const { auth } = state;
	return {
		...action,
		endpoint: getUrl(action.endpoint),
		headers: {
			...action.headers,
			"Content-type": "application/json",
			Accept: "application/json",
			Authorization:` Bearer ${auth.token}`
		}
	};
};

**Comment by marcin-piela** [comment]
At first glance it looks ok (token is fetched from store on every request to API), could you provide an example on codesandbox?

**Comment by marcin-piela** [comment]
Closed due to inactivity

**Comment by BenQoder** [comment]
I Still Face This Issue, Just That I Found Another Way To Fix My Initial Problem.

I Will Reproduce The Issue  On Codesandbox When I Have Time
