### ISSUE TITLE
[Feature Request] custom client fetch

### ISSUE THREAD

**Issue by Jekiwijaya** [marcin-piela/react-fetching-library#46]
It would be great if createClient able to accept the other client fetch like `axios`.

I will make pull request when I have time

**Comment by marcin-piela** [comment]
Yeah, I've got it in my head :) Please remember to make this PR here https://github.com/marcin-piela/fetching-library, cause in v2.0 react-fetching-library will be divided into 2 libs

**Comment by marcin-piela** [comment]
Implemented in PR #53

**Comment by marcin-piela** [comment]
Released in 1.5.10

**Comment by PaulTime** [comment]
@marcin-piela , hello, first of all i would like to say ''Thank you a lot for this work that you have done!'' . I wanted to ask here about one moment: I need to get upload/download progress when I'm fetching, but as I see in [createClient config](https://marcin-piela.github.io/react-fetching-library/#/?id=how-to-create-instance-of-client) or directly in [source code](https://github.com/marcin-piela/react-fetching-library/blob/master/src/client/client.ts#L67) there is no way to get those metrics somehow. I am using axios, and can't find the way that it should be integrated in createClient.query option.

Maybe you have any ideas or anybody else has one.

Best wishes. :)

**Comment by marcin-piela** [comment]
You have to pass `onDownloadProgress` function to axios

```js
import axios, { AxiosInstance, Method } from 'axios';

export const buildAxiosFetch = (axiosInstance: AxiosInstance) => async (init: RequestInfo, options?: RequestInit) => {
  const cancelSource = axios.CancelToken.source();

  const config = {
    url: init as string,
    method: (options && options.method ? options.method : 'GET') as Method,
    onDownloadProgress: options.onDownloadProgress,
    data: options && options.body ? options.body : undefined,
    headers:
      options && options.headers
        ? Object.keys(options.headers).reduce((destination, key) => {
            // @ts-ignore
            destination[key.toLowerCase()] = options.headers[key];
            return destination;
          }, {})
        : undefined,
    validateStatus: () => true,
    cancelToken: cancelSource.token,
  };

  if (options && options.signal) {
    options.signal.onabort = () => {
      cancelSource.cancel('Operation canceled from hook');
    };
  }

  const result = await axiosInstance.request(config);
  const responseBody = typeof result.data === `object` ? JSON.stringify(result.data) : result.data;
  const headers = new Headers();

  Object.entries(result.headers).forEach(function([key, value]) {
    headers.append(key, value as string);
  });

  return new Response(responseBody, {
    status: result.status,
    statusText: result.statusText,
    headers,
  });
};
```


```

const response = useQuery({
    endpoint: '/',
    method: 'GET',
    onDownloadProgress: function(progressEvent) {
        console.log('download', progressEvent);
      }
})

```

**Comment by PaulTime** [comment]
@marcin-piela, hmm, but Property 'onDownloadProgress' does not exist on type 'RequestInit'.

**Comment by marcin-piela** [comment]
I get it so I'll need to change types in library itself but for now just use `any` in that place

**Comment by PaulTime** [comment]
so as i understood, for now even if I use `options?: any` it won't work because 
```
const response = await fetchFunction(endpoint, {
          body: body ? (shouldStringify ? JSON.stringify(body) : body) : undefined,
          cache: options.cache,
          credentials: options.credentials,
          headers,
          integrity: options.integrity,
          keepalive: options.keepalive,
          method: options.method,
          mode: options.mode,
          redirect: options.redirect,
          referrer: options.referrer,
          referrerPolicy: options.referrerPolicy,
          signal: options.signal,
          window: options.window,
        });
```
`options?: any` doesn't contain onDownloadProgress/onUploadProgress property in latest version

**Comment by marcin-piela** [comment]
Ahhh exactly, I'll try to change it later today

**Comment by PaulTime** [comment]
ok, thanks a lot ;)

**Comment by marcin-piela** [comment]
@PaulTime releases in 1.7.1

Check out updates example:
https://github.com/marcin-piela/react-fetching-library/blob/master/examples/with-axios/src/rfc-extended.d.ts - this file is needed to add to action interfaces new params (ie. onDownloadProgress)

https://github.com/marcin-piela/react-fetching-library/blob/master/examples/with-axios/src/usersList/UsersListContainer.tsx - example of use onDownloadProgress

https://github.com/marcin-piela/react-fetching-library/blob/master/examples/with-axios/src/api/buildAxiosFetch.ts

**Comment by PaulTime** [comment]
@marcin-piela, its strange, because now I can't download any image or buffer data. I've created a [sandbox](https://codesandbox.io/s/modest-pond-q8cq0) where you can see in App.js file window.fetch logs to console valid url for image that was fetched, but its not true for useClient api :(.
I think maybe its because of [this line in souces](https://github.com/marcin-piela/react-fetching-library/blob/master/src/client/client.ts#L116) but I find it difficult for me to tell if it is. 
Maybe you could give me an answer.

**Comment by marcin-piela** [comment]
It's working on my side 😄 
```
fetch blob:https://q8cq0.csb.app/6c9b6a63-8aed-4a47-8314-cf8f41258c04 index.js:27
client blob:https://q8cq0.csb.app/642067c3-2f0d-4038-b9cd-14fdcdebf332
```
Maybe your sandbox cached old version of react-fetching-library?

**Comment by PaulTime** [comment]
hmm, I tried in incognito, and its going this way -_-)
[Screen Recording 2020-03-24 at 13.43.56.zip](https://github.com/marcin-piela/react-fetching-library/files/4375007/Screen.Recording.2020-03-24.at.13.43.56.zip)

**Comment by marcin-piela** [comment]
My mistake :( Check 1.7.2 version and this sandbox https://codesandbox.io/s/awesome-wu-n5yc7 I've changed index.js file (check manually if 1.7.2 is installed here as well)

**Comment by PaulTime** [comment]
yeah, the sandbox worked for me, let me check it in my project, but seems like it should be working now)
