### ISSUE TITLE
Support for binary responses

### ISSUE THREAD

**Issue by Sjiep** [marcin-piela/react-fetching-library#56]
Looking at the [code](https://github.com/marcin-piela/react-fetching-library/blob/master/src/client/client.ts#L77), the library currently will parse the responses to either `text` or `json`.  However for our application we need to also support binary data (such as images and PDF's).

Am I correct that a binary response (`ArrayBuffer` or `Blob`) currently is not supported? If so I would like to implemented such a feature and create a PR for it.

@marcin-piela would you have any thoughts on the implementation? Maybe we can add a [`responseType`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType) property as part of the `Action` interface...?

**Comment by marcin-piela** [comment]
Good catch @Sjiep 

I think the easiest option will be to add checking [here](https://github.com/marcin-piela/react-fetching-library/blob/master/src/client/client.ts#L77) whether the response is binary data, text or json and then run response.blob() on it 🤔 

In next version (react-fetching-library split to 2 separated libs) will be easier to handle different response types, cause the logic will be moved to interceptors [here](https://github.com/marcin-piela/fetching-library/blob/master/src/client/client.ts#L53)

**Comment by Sjiep** [comment]
@marcin-piela  Yes, that was what I was looking at!

It could be part of the default behaviour, such that you don't have to implement it separately when you don't want any custom behaviour. 

I'll have a go at it and make a PR, if that is OK with you.

**Comment by marcin-piela** [comment]
yeah it’s great 👍
