### ISSUE TITLE
useMutation vs useQuery

### ISSUE THREAD

**Issue by Sjiep** [marcin-piela/react-fetching-library#58]
Just a quick question regarding the hooks `useMutation` and `useQuery`. 

What is the main difference between the two? If I set the `initFetch` param of `useQuery` to `false` the hooks seems to behave very similar to what `useMutation` is doing. Am I correct on that?

**Comment by marcin-piela** [comment]
@Sjiep we can say that is very similar, but `useMutation` was created to handle POST,PUT,PATCH requests like form submit etc, cause we don't want to store BODY value in state, it's better to send it directly with useMutation.mutate

Example 
https://codesandbox.io/s/github/marcin-piela/react-fetching-library/tree/master/examples/crud-form

**Comment by Sjiep** [comment]
> cause we don't want to store BODY value in state
Ok, that makes sense, thanks. 

I might make a PR for typing the return value of the `useMutation` hook (similar to what I did for the `useQuery)

**Comment by marcin-piela** [comment]
@Sjiep you can add it directly in TS code however generated typings should work fine:

`useMutation.d.ts`
```js
export declare const useMutation: <T = any, R = {}, S = any>(actionCreator: ActionCreator<S, R>) => {
    status?: number | undefined;
    error: boolean;
    errorObject?: any;
    payload?: T | undefined;
    headers?: Headers | undefined;
    abort: () => void;
    loading: boolean;
    mutate: (action: S) => Promise<QueryResponse<T>>;
    reset: () => void;
};
```

**Comment by Sjiep** [comment]
Mmm, our current lint setup requires function explicitly to type the return value of a function and we are using the hooks from this library in custom hooks.

Alternatively I could define the type/interface myself....

**Comment by marcin-piela** [comment]
Ok so feel free to open newt PR then 👍

**Comment by maxtotheguenther** [comment]
@marcin-piela. I was also wondering about that implementation. Sometimes you want to trigger a Get Call later with an Id you don't have when you mount the hook. Is it then the correct procedure to use the hook useMutation? Otherwise I do not know how to do it with the hook useQuery (Since useQuery is expecting a final Action). If you want I can code an example.

**Comment by marcin-piela** [comment]
@maxtotheguenther yes please show me an example in codesandbox

Sometimes I just use `useClient` directly:

```ts
import { useClient } from 'react-fetching-library';

.....

const { query } = useClient();
const [ user, setUser ] = useState(undefined);
const [ isLoading, setLoading ] = useState(true);

useEffect(async() => {
   const { payload: user, loading, error } = await query(fetchUserAction(userId))
   setLoading(false);
   setUser(user);
}, [userId]);

```

Or you can use `useQuery` with second parameter as `false`

```ts
import { useQuery } from 'react-fetching-library';

.....

const { query: fetchUser, payload: user, loading: isLoading, error: isError } = useQuery(fetchUserAction(userId), false);

useEffect(() => {
   if (userId) {
     fetchUser();
   }
}, [userId]);

```

**Comment by maxtotheguenther** [comment]
Hey @marcin-piela ,
instead of using useClient directly i thought that you can give the useQuery a callback (if lazy loading is set to false) which you can execute later with an asynchronous parameter. Actually analogous to useMutation.
I made a code snippet for this:

```javascript
import React from "react";
import {
  ClientContextProvider,
  createClient,
  useQuery,
  useClient
} from "react-fetching-library";
import "./styles.css";

const getId = () =>
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(1);
    }, 3000);
  });

export default function App() {
  return (
    <ClientContextProvider
      client={createClient({
        requestInterceptors: [],
        responseInterceptors: []
      })}
    >
      {/*<NiceToHaveDemo />*/}
      <UseClientDirectly />
    </ClientContextProvider>
  );
}
const fetchUserListCallback = id => ({
  method: "GET",
  endpoint: `https://jsonplaceholder.typicode.com/todos/${id}`
});

// Would be nice to have.
function NiceToHaveDemo() {
  // Analogous to usemutation. useQuery expects a callback func if u set second parameter to false
  const { query } = useQuery(fetchUserListCallback, false);

  // like useMutation.mutate(something)
  const triggerCall = async () => {
    const id = await getId();
    query(id);
  };

  return (
    <React.Fragment>
      <button onClick={triggerCall}>trigger</button>
    </React.Fragment>
  );
}

function UseClientDirectly() {
  const { query } = useClient();
  const triggerCall = async () => {
    const id = await getId();
    query(fetchUserListCallback(id));
  };
  return (
    <React.Fragment>
      <button onClick={triggerCall}>trigger</button>
    </React.Fragment>
  );
}
```

**Comment by marcin-piela** [comment]
https://marcin-piela.github.io/react-fetching-library/#/?id=useparametrizedquery
