### ISSUE TITLE
useSuspenseQuery using global cache

### ISSUE THREAD

**Issue by fabianishere** [marcin-piela/react-fetching-library#66]
Hi,

I have been using this library for data fetching in a Suspense-enabled React application I am building. However, it occurred to me that `useSuspenseQuery` does not use the `cacheProvider` given to the client, but instead uses a global cache.

https://github.com/marcin-piela/react-fetching-library/blob/ae87931f4693232a6d713b2cdd511f11d638e579/src/hooks/useSuspenseQuery/useSuspenseQuery.ts#L12

https://github.com/marcin-piela/react-fetching-library/blob/ae87931f4693232a6d713b2cdd511f11d638e579/src/hooks/useSuspenseQuery/useSuspenseQuery.ts#L17

Is there any reason why `useSuspenseQuery` uses a global cache instead of the cache from the client? In my case, I cannot share caches/clients between requests as to prevent sensitive information from leaking between requests.

**Comment by marcin-piela** [comment]
It uses both (context from client and context created for suspense purposes), global context is needed in the same way as in react-cache (to throw promise correctly)

https://github.com/facebook/react/blob/40568e9773276d94e6aa5b70fed4355a7291827f/packages/react-cache/src/ReactCache.js#L88

**Comment by fabianishere** [comment]
Hmm interesting. Is it still possible to tie the cache to a client? Although a global cache isn’t an issue for the browser, on the server we should not be sharing caches across requests.

**Comment by marcin-piela** [comment]
For now it's not, I will try to rewrite that suspense cache in this week and connect it with client instance (instead of global variable) - it will resolve that issue.

**Comment by fabianishere** [comment]
Great! Let me know if you need any help!

**Comment by marcin-piela** [comment]
@fabianishere please check the new version

fell free to reopen that issue when needed
