### ISSUE TITLE
useBulkMutate hook

### ISSUE THREAD

**Issue by josejulio** [marcin-piela/react-fetching-library#72]
Provide useBulkMutate hook to allow define multiple actions, e.g. if calling a bulk edits or deletes on a single hook.

```
const {mutate} = useMultipleMutate(createAction);

const handleSubmit = (values) => {
    const response = await mutate(values); // values is (e.g.) an array of ids
}
```

**Comment by josejulio** [comment]
@marcin-piela I'm needing this. 
If you don't have any plans to work on this I could start working on it.
I could implement basing on the `useMutation` hook.

Also, do you have any release cadence?

**Comment by marcin-piela** [comment]
@josejulio yes you can start working on it. I recommend to implement it first in your project as a custom hook and then in the library. You have to think how to deal with errors (ie. 10 requests success, 2 failed) 

No we don't have it.

**Comment by josejulio** [comment]
> @josejulio yes you can start working on it. I recommend to implement it first in your project as a custom hook and then in the library. You have to think how to deal with errors (ie. 10 requests success, 2 failed)

Sure, thanks!
